### ISSUE TITLE
Install from private git repo prompts for password, doesn't use SSH key 

### ISSUE THREAD

**Issue by victornswd** [gdotdesign/elm-github-install#12]
I'm trying to install a package from a private repo and elm-install prompts for a password even though I have a working SSH key set up with the server. Cloning the repo manually using the same URL works without any issues.

**Comment by gdotdesign** [comment]
Can you show me how did you set up the URL for the repository? I suspect if using the **https** version it prompts for password.

**Comment by victornswd** [comment]
This is how I have the `dependency-souces` set up:
```
    "dependencies": {
        ...
        "user/repo" : "1.0.0 <= v < 2.0.0"
    },
    "dependency-sources": {
      "user/repo": {
        "url": "ssh://<gituser>@<gitserver>:233/user/repo",
        "ref": "master"
      }
    },
```

**Comment by gdotdesign** [comment]
Can you provide some more information please? 
* which OS / architecture you are using? 
* what is the output look like?
* is the installation successful after providing the password?

I've only tested installation of private repositories on Linux (Ubuntu 16.04 and 14.04) which were successful.

Thanks

**Comment by victornswd** [comment]
I'm trying to connect from an Ubuntu to a [gitolite](http://gitolite.com/gitolite/index.html) installation on an Ubuntu machine. On further inspection, this might be a problem caused by gitolite, seeing how gitolite uses it's own custom shell. I still can't install the repo after providing a password. 

I will test things out further tomorrow, with a local gitolite.

**Comment by gdotdesign** [comment]
Didn't have activity for 30 days, closing. If there is any update please reopen this issue.
