### ISSUE TITLE
EACCES: permission denied, mkdir '/Users/Chadtech/.elm-install/elm-install-0.3.1-osx'

### ISSUE THREAD

**Issue by Chadtech** [gdotdesign/elm-github-install#13]
Hi,

I am having some difficulty installing this. with the command `sudo npm install elm-github-install -g`, I get an access error. Npm tells me the install fails on scripts/install.js. I am on a mac.

**Comment by gdotdesign** [comment]
Hey, sorry for the late response. If you are having trouble installing from either rubygems or npm there are binaries uploaded in the releases page for every release: https://github.com/gdotdesign/elm-github-install/releases

**Comment by gdotdesign** [comment]
Didn't get a response for 30 days, closing.
