### ISSUE TITLE
Aliasing a package from a forked repository

### ISSUE THREAD

**Issue by mrozbarry** [gdotdesign/elm-github-install#16]
Just to start off, the problem may not actually be with elm-github-install, but instead with the elm native naming convention.

I'm using a library in elm-community that I am also contributing to (without write access, just via PRs). This repo implements a native module, and that works.  I own an unmerged branch that I need features from.

My issue is that native modules force the naming `_packageOwner$packageName$path$Native_Thing`.

When I try "mrozbarry/packageName" in my elm-package.json, I can install, but elm can't find the correct native code, which is "_originalAuthor$packge_name" and elm is looking for "_mrozbarry$package_name"

```
"dependencies": {
  "mrozbarry/canvas": "..."
},
"dependency-sources": {
  "mrozbarry/canvas": {
    "url": "git@github.com/mrozbarry/canvas",
    "ref": "draw-image"
  }
}
```

elm-github-install throws an error when I try aliasing like this:

```
"dependencies": {
  "elm-community/canvas": "..."
},
"dependency-sources": {
  "elm-community/canvas": {
    "url": "git@github.com/mrozbarry/canvas",
    "ref": "draw-image"
  }
}
```

```
$ elm-install
Resolving packages...

  The source of package elm-community/canvas is set to https://github.com/mrozbarry/canvas which would
  be install to elm-stuff/mrozbarry/canvas. This would cause a conflict
  when trying to compile anything.

  The name of a package must match the source url's path.

  elm-community/canvas <=> mrozbarry/canvas
```

Any reason your git clone couldn't do something like `git clone gitUrl packageOwnerAndName`?

**Comment by gdotdesign** [comment]
Yes this is a limitation at the moment which I looked into while ago and made some headway in this PR: https://github.com/gdotdesign/elm-github-install/pull/14 also see the discussion here https://groups.google.com/d/msg/elm-discuss/eusppnDgN-A/mf1L08NRCAAJ

The code works and I could successfully install `elm-lang/core` from a fork and even from locally in the file system. I didn't have time to finish (specs, documenation, etc), I will probably get to it soon™

If you really need this feature right now then I suggest the you install the gem from that branch.

**Comment by gdotdesign** [comment]
I've made progress on this in #23. I've rewritten how sources are used, so this and using local packages will be available when it releases.

**Comment by gdotdesign** [comment]
This is now available in https://github.com/gdotdesign/elm-github-install/releases/tag/v1.0.0
