### ISSUE TITLE
error on install this package truqu/elm-base64

### ISSUE THREAD

**Issue by helderjnpinto** [gdotdesign/elm-github-install#18]
on install this package i get un error like 
`
elm-install         
Resolving packages...
  ▶ Package: https://github.com/truqu/elm-base64 is outdated, fetching changes...
  ▶ Package: https://github.com/maxsnew/IO is outdated, fetching changes...
  ▶ Package: https://github.com/deadfoxygrandpa/Elm-Test is outdated, fetching changes...
  ▶ Package: https://github.com/laszlopandy/elm-console is outdated, fetching changes...
  ▶ Package: https://github.com/NoRedInk/elm-check is outdated, fetching changes...
  ▶ Package: https://github.com/NoRedInk/elm-random-extra is outdated, fetching changes...
...
and continues ...
`
http://package.elm-lang.org/packages/truqu/elm-base64/latest/Base64

**Comment by gdotdesign** [comment]
Can you show your `elm-package.json` file? it should help debugging this issue.

**Comment by helderjnpinto** [comment]
@gdotdesign 
`
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/user/project.git",
    "license": "BSD3",
    "source-directories": [
        ".",
        "src"
        ],
    "exposed-modules": [],
    "dependencies": {
        "Digisensei/elm-phoenix-socket": "2.0.1 < v < 3.0.0",
        "NoRedInk/elm-decode-pipeline": "3.0.0 <= v < 4.0.0",
        "elm-lang/core": "5.1.1 <= v < 6.0.0",
        "elm-lang/dom": "1.1.1 <= v < 2.0.0",
        "elm-lang/html": "2.0.0 <= v < 3.0.0",
        "elm-lang/http": "1.0.0 <= v < 2.0.0",
        "elm-lang/keyboard": "1.0.1 <= v < 2.0.0",
        "elm-lang/mouse": "1.0.1 <= v < 2.0.0",
        "elm-lang/page-visibility": "1.0.1 <= v < 2.0.0",
        "elm-lang/window": "1.0.1 <= v < 2.0.0",
        "evancz/url-parser": "2.0.1 <= v < 3.0.0",
        "jystic/elm-font-awesome": "2.0.1 <= v < 3.0.0",
        "truqu/elm-base64": "1.0.0 <= v < 2.0.0"
    },
    "elm-version": "0.18.0 <= v < 0.19.0"
}

`

**Comment by gdotdesign** [comment]
For me it's working properly, did you wait until it's finished? the output your provided is normal.

Using a different cache directory `elm-install --cache-directory=cache` (the default is `~/.elm-install`) shows me this output:
```
Resolving packages...
  ▶ Package: https://github.com/Digisensei/elm-phoenix-socket not found in cache, cloning...
  ▶ Package: https://github.com/elm-lang/core not found in cache, cloning...
  ▶ Package: https://github.com/elm-lang/html not found in cache, cloning...
  ▶ Package: https://github.com/elm-lang/virtual-dom not found in cache, cloning...
  ▶ Package: https://github.com/elm-lang/websocket not found in cache, cloning...
  ▶ Package: https://github.com/NoRedInk/elm-decode-pipeline not found in cache, cloning...
  ▶ Package: https://github.com/evancz/elm-effects not found in cache, cloning...
  ▶ Package: https://github.com/elm-lang/dom not found in cache, cloning...
  ▶ Package: https://github.com/elm-lang/http not found in cache, cloning...
  ▶ Package: https://github.com/elm-lang/keyboard not found in cache, cloning...
  ▶ Package: https://github.com/elm-lang/mouse not found in cache, cloning...
  ▶ Package: https://github.com/elm-lang/page-visibility not found in cache, cloning...
  ▶ Package: https://github.com/elm-lang/window not found in cache, cloning...
  ▶ Package: https://github.com/evancz/url-parser not found in cache, cloning...
  ▶ Package: https://github.com/elm-lang/navigation not found in cache, cloning...
  ▶ Package: https://github.com/jystic/elm-font-awesome not found in cache, cloning...
  ▶ Package: https://github.com/evancz/elm-html not found in cache, cloning...
  ▶ Package: https://github.com/evancz/virtual-dom not found in cache, cloning...
  ▶ Package: https://github.com/evancz/elm-svg not found in cache, cloning...
  ▶ Package: https://github.com/elm-lang/svg not found in cache, cloning...
  ▶ Package: https://github.com/truqu/elm-base64 not found in cache, cloning...
  ▶ Package: https://github.com/maxsnew/IO not found in cache, cloning...
  ▶ Package: https://github.com/deadfoxygrandpa/Elm-Test not found in cache, cloning...
  ▶ Package: https://github.com/laszlopandy/elm-console not found in cache, cloning...
  ▶ Package: https://github.com/NoRedInk/elm-check not found in cache, cloning...
  ▶ Package: https://github.com/NoRedInk/elm-random-extra not found in cache, cloning...
  ▶ Package: https://github.com/NoRedInk/elm-task-extra not found in cache, cloning...
  ▶ Package: https://github.com/NoRedInk/elm-shrink not found in cache, cloning...
  ▶ Package: https://github.com/NoRedInk/elm-lazy-list not found in cache, cloning...
  ▶ Package: https://github.com/maxsnew/lazy not found in cache, cloning...
  ▶ Package: https://github.com/TheSeamau5/elm-lazy-list not found in cache, cloning...
  ▶ Package: https://github.com/TheSeamau5/elm-random-extra not found in cache, cloning...
  ▶ Package: https://github.com/TheSeamau5/elm-task-extra not found in cache, cloning...
  ▶ Package: https://github.com/deadfoxygrandpa/elm-test not found in cache, cloning...
Solving dependencies...
Saving package cache...
  ● Digisensei/elm-phoenix-socket - 2.0.2 (2.0.2)
  ● NoRedInk/elm-decode-pipeline - 3.0.0 (3.0.0)
  ● elm-lang/core - 5.1.1 (5.1.1)
  ● elm-lang/dom - 1.1.1 (1.1.1)
  ● elm-lang/html - 2.0.0 (2.0.0)
  ● elm-lang/http - 1.0.0 (1.0.0)
  ● elm-lang/keyboard - 1.0.1 (1.0.1)
  ● elm-lang/mouse - 1.0.1 (1.0.1)
  ● elm-lang/page-visibility - 1.0.1 (1.0.1)
  ● elm-lang/window - 1.0.1 (1.0.1)
  ● evancz/url-parser - 2.0.1 (2.0.1)
  ● jystic/elm-font-awesome - 2.0.1 (2.0.1)
  ● truqu/elm-base64 - 1.0.5 (1.0.5)
  ● elm-lang/virtual-dom - 2.0.4 (2.0.4)
  ● elm-lang/navigation - 2.1.0 (2.1.0)
  ● elm-lang/websocket - 1.0.2 (1.0.2)
  ● elm-lang/svg - 2.0.0 (2.0.0)
Packages configured successfully!
```

**Comment by helderjnpinto** [comment]
the question is i make a project find for packages like "deadfoxygrandpa/elm-test" but i not use! why elm-install is search for that

**Comment by gdotdesign** [comment]
You can read about how `elm-github-install` works in this document: https://github.com/gdotdesign/elm-github-install/blob/master/docs/How%20it%20works.md but basically it creates a cache of the packages that you use or used. 

This cache is just the clones of the repositories in `~/.elm-install` directory. It allows among other thigns for offline installation of packages.

 In this case `deadfoxygrandpa/elm-test` is cloned because some version of some package uses it as a dependency.

**Comment by helderjnpinto** [comment]
OK. Thanks. I'll see what the problem is.

**Comment by helderjnpinto** [comment]
yes now its working, but If I remove the line for this base64 package, delete folder elm-stuff, elm-install does not show these packages I speak, and the base64 package does not have this dependencies  https://github.com/truqu/elm-base64/blob/master/elm-package.json.

**Comment by gdotdesign** [comment]
Yes you are right the latest version does not depend on it, but **elm-github-install** goes through all versions of it and since the 1.0.0 (https://github.com/truqu/elm-base64/blob/1.0.0/elm-package.json) has that dependency it clones it.

**Comment by helderjnpinto** [comment]
ok, i resolve this issue put   "truqu/elm-base64": "1.0.5 <= v < 2.0.0" to get only last version... thanks
