### ISSUE TITLE
Installing via Yarn bin doesn't work

### ISSUE THREAD

**Issue by dustinfarris** [gdotdesign/elm-github-install#19]
Maybe via npm also, I didn't check

On ubuntu 16.04

```console
$ sudo apt install ruby
$ yarn add -D elm-github-install
$ node_modules/elm-github-install/bin/elm-install
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- commander/import (LoadError)
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from node_modules/elm-github-install/bin/elm-install:4:in `<main>'
```

**Comment by gdotdesign** [comment]
The node version uses https://github.com/phusion/traveling-ruby to provide a separate ruby runtime so having ruby installed is not a requirement. During installation the node version downloads this packaged version and extracts it to a new directory in `~/.elm-install/`.

You can run the proper binary with `yarn elm-install` or `yarn run elm-install`.

Alternatively If you already have ruby installed then you can install the gem with `gem install elm-install` or you can download the compiled package from the [releases](https://github.com/gdotdesign/elm-github-install/releases) page.

**Comment by dustinfarris** [comment]
Thanks, that worked.

```
yarn add -D elm-github-install
yarn run github-install
```
