### ISSUE TITLE
Solving dependencies fails.

### ISSUE THREAD

**Issue by rupertlssmith** [gdotdesign/elm-github-install#31]
Solving dependencies fails with this error:

`Solving dependencies...
/var/lib/gems/2.3.0/gems/solve-3.1.0/lib/solve/ruby_solver.rb:80:in `block in resolve': undefined method `name' for nil:NilClass (NoMethodError)
        from /var/lib/gems/2.3.0/gems/solve-3.1.0/lib/solve/ruby_solver.rb:79:in `each'
        from /var/lib/gems/2.3.0/gems/solve-3.1.0/lib/solve/ruby_solver.rb:79:in `inject'
        from /var/lib/gems/2.3.0/gems/solve-3.1.0/lib/solve/ruby_solver.rb:79:in `resolve'
        from /var/lib/gems/2.3.0/gems/solve-3.1.0/lib/solve.rb:64:in `it!'
        from /var/lib/gems/2.3.0/gems/elm_install-1.1.0/lib/elm_install/installer.rb:40:in `results'
        from /var/lib/gems/2.3.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /var/lib/gems/2.3.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
        from /var/lib/gems/2.3.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /var/lib/gems/2.3.0/gems/elm_install-1.1.0/lib/elm_install/installer.rb:26:in `install'
        from /var/lib/gems/2.3.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /var/lib/gems/2.3.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
        from /var/lib/gems/2.3.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /var/lib/gems/2.3.0/gems/elm_install-1.1.0/lib/elm_install.rb:41:in `install'
        from /var/lib/gems/2.3.0/gems/elm_install-1.1.0/bin/elm-install:18:in `block (2 levels) in <top (required)>'
        from /var/lib/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
        from /var/lib/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
        from /var/lib/gems/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
        from /var/lib/gems/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
        from /var/lib/gems/2.3.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
        from /var/lib/gems/2.3.0/gems/commander-4.4.3/lib/commander/import.rb:5:in `block in <top (required)>'
`

=== Running 'ruby --version' reports:
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]

Any other things I can report to help diagnose the problem, please let me know.

I just upgraded my system to Debian 9 from 8, was all working previously. I guess a version of something is diferent now...

**Comment by rupertlssmith** [comment]
Here is an elm-package.json that it fails on:

`{
    "version": "0.0.1",
    "summary": "Auth Server UI",
    "repository": "https://github.com/no-user/not-a-github-project.git",
    "license": "private",
    "source-directories": [
        "src/elm",
        "src/auth-client/elm"
    ],
    "exposed-modules": [],
    "native-modules": true,
    "dependencies": {
        "elm-lang/core": "5.0.0 <= v < 6.0.0",
        "elm-lang/html": "2.0.0 <= v < 3.0.0",
        "elm-lang/navigation": "2.0.1 <= v < 3.0.0",
        "elm-lang/http": "1.0.0 <= v < 2.0.0",
        "rgrempel/elm-http-decorators": "2.0.0 <= v < 3.0.0",
        "debois/elm-mdl": "8.1.0 <= v < 9.0.0",
        "elm-community/json-extra": "2.0.0 <= v < 3.0.0",
        "elm-community/dict-extra": "1.3.1 <= v < 2.0.0",
        "elm-community/maybe-extra": "3.0.0 <= v < 4.0.0",
        "elm-community/list-extra": "4.0.0 <= v < 5.0.0",
        "krisajenkins/elm-exts": "26.1.0 <= v < 27.0.0",
        "rgrempel/elm-route-url": "3.0.0 <= v < 4.0.0",
        "rupertlssmith/elmq": "1.0.0 <= v < 2.0.0",
        "rupertlssmith/elm-auth": "1.0.0 <= v < 2.0.0"        
    },
    "elm-version": "0.18.0 <= v < 0.19.0"
}
`

**Comment by rupertlssmith** [comment]
[elm-package.txt](https://github.com/gdotdesign/elm-github-install/files/1183624/elm-package.txt)

**Comment by gdotdesign** [comment]
Couple of questions:
* are you using it as a gem?
* did the same `elm-package.json` work on Debian 8?

**Comment by rupertlssmith** [comment]
Yes I installed it as a ruby gem.
It did work on Debian 8 (ruby 2.1.5) just fine, but not this version of elm-install, I was running something older but not sure what.

**Comment by gdotdesign** [comment]
Managed to reproduce it. I'll look into it and get back to you.

**Comment by gdotdesign** [comment]
Yes some dependency changed and causing this bug. Until I can fix it I recommend using the npm package or the binaries that are available in the releases page.

**Comment by rupertlssmith** [comment]
Thanks. Unfortunately npm won't install as per the other issue. I tried downloading the binaries, but they also do not run, or I do not understand how to install them and use them (tried unpackaging under /opt and running there).

**Comment by gdotdesign** [comment]
Released [`v1.1.1`](https://rubygems.org/gems/elm_install/versions/1.1.1) on rubygems with the fix. Let me know if it works.

**Comment by rupertlssmith** [comment]
Thanks, 1.1.1 installs as a gem and the issue is fixed. Thanks for sorting it so quickly.
