### ISSUE TITLE
Return code

### ISSUE THREAD

**Issue by kfish** [gdotdesign/elm-github-install#38]
I often chain commands together, like:

  $ elm-install && make ...

then get coffee.

It seems elm-install always returns success (exitcode 0):

```
conrad@spitfire:~/src/elm/dreambuggy$ elm-install
...
Solving dependencies...
  ▶ No solution found: Unable to satisfy the following requirements:

- `here4/here4 (< 4.0.0)` required by `user-specified dependency`
- `here4/here4 (>= 3.3.8)` required by `user-specified dependency`
conrad@spitfire:~/src/elm/dreambuggy$ echo $?
0
```

so the commandline chain doesn't work: if I do "elm-install && make" then make should not run.

**Comment by gdotdesign** [comment]
Thanks for bringing this up, fixed in 1.4.0 - https://github.com/gdotdesign/elm-github-install/releases/tag/v1.4.0
