### ISSUE TITLE
Can we have an option so it won't clone already-existing/"official"/public packages (like elm-lang/core etc)?

### ISSUE THREAD

**Issue by metaleap** [gdotdesign/elm-github-install#45]
That option would either skip all `dependencies` that already reside in `./elm-stuff/packages` (but I guess wouldn't work well for package updates then?) or perhaps check the official package.elm-lang.org (I guess checking for 404 when hitting `http://package.elm-lang.org/packages/FOO/BAR/latest` might suffice).

I hoped the new `--only-update` would be a way to prevent `elm-install` from grabbing and "updating" all the official packages (where I'd want to stick to the `elm-make` repo sources really), but no dice!

    [00:15 rox ~/c/e/mokka-app]$ elm-install install --only-update aforemny/elm-mdc
    Resolving packages...
      ▶ Getting updates for: aforemny/elm-mdc
      ▶ Package: https://github.com/elm-lang/core not found in cache, cloning...
      ▶ Package: https://github.com/elm-lang/html not found in cache, cloning...
    ^C

Great tool though!  =)

**Comment by gdotdesign** [comment]
I don't really understand the use case you are having, it's any of these?:
- You install packages with `elm-package` and want to install some with `elm-install`?
- You want `elm-install` to use the official package repository?

`--only-update` is for skipping `git fetch` in currently cloned repositories except the one given, there is `--skip-update` with skips `git fetch` for all cloned repositories.

> (I guess checking for 404 when hitting http://package.elm-lang.org/packages/FOO/BAR/latest might suffice

It would if we only cloud install versions, but we can install any git refs like `master`, `development`, `3995aee6009629f961`, etc. so there is really only one way to update a package reliably.

**Comment by metaleap** [comment]
I think it was a bit late last night, I had some misconceptions or something. Didn't like "at first glance" that `elm-lang` repos (or generally any dep that was already properly resolved and sitting ready inside `elm-stuff`) were cloned from Github in a moment of "oh no, it will override the 'offical' working current-version release with some whack work-in-progress state from the git repo". But that's silly of course because we have version numbers in our `elm-package.json`s... 😏 furthermore of course `elm-install` doesn't *build/make* anything, here my subconscious was associating with other `xyz install` tools (like Go's) that typically *do*. So disregard  =)
