### ISSUE TITLE
Over-reliance on cache

### ISSUE THREAD

**Issue by simonh1000** [gdotdesign/elm-github-install#52]
I just used elm-install for the first time in a while, and the library I wanted to access had had several updates since my last use. What was installed was the old cached version, and the only way I could find around it was to change my elm-package.json to use the latest version.

Surely there should be some sort of check of cached versions vs what's on github?

**Comment by gdotdesign** [comment]
It seems to me like you are using an old version.

In [1.1.0](https://github.com/gdotdesign/elm-github-install/releases/tag/v1.1.0) changes for the repositories are checked on every install. 
In [1.6.0](https://github.com/gdotdesign/elm-github-install/releases/tag/v1.6.00) two flags were added to either skip checking or just update only one dependency.

If you are using the latest version and it's still not updating that it's probably a bug.

**Comment by simonh1000** [comment]
whoops!
