### ISSUE TITLE
elm-install not working with elm-mdl

### ISSUE THREAD

**Issue by alexpreiss** [gdotdesign/elm-github-install#66]
I've seen a very similar issue to this, where Aux.elm doesn't work. However that
issue was solved when you changed the file name to Helper.elm. I'm not sure why I'm still getting this error, I tried installing the latest version but it didn't work.

Heres the trace

λ elm-github-install --trace
Resolving packages...
  ▶ Getting updates for: debois/elm-mdl
C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/git-1.3.0/lib/git/lib.rb:937:in `command': git "--git-dir=C:/Users/code/.elm-install/github.com/debois/elm-mdl/.git" "--work-tree=C:/Users/code/.elm-install/github.com/debois/elm-mdl" reset "--hard"  2>&1:error: unable to create file src/Material/Aux.elm (No such file or directory) (Git::GitExecuteError)
fatal: Could not reset index file to revision 'HEAD'.
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/git-1.3.0/lib/git/lib.rb:562:in `reset'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/git-1.3.0/lib/git/base.rb:242:in `reset_hard'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/elm_install-1.6.1/lib/elm_install/repository.rb:85:in `repo'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/elm_install-1.6.1/lib/elm_install/repository.rb:101:in `fetch'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/elm_install-1.6.1/lib/elm_install/git_source.rb:100:in `versions'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/elm_install-1.6.1/lib/elm_install/resolver.rb:45:in `resolve_dependency'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/elm_install-1.6.1/lib/elm_install/resolver.rb:28:in `block in resolve'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/elm_install-1.6.1/lib/elm_install/resolver.rb:27:in `each'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/elm_install-1.6.1/lib/elm_install/resolver.rb:27:in `resolve'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/elm_install-1.6.1/lib/elm_install/installer.rb:25:in `install'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_reference.rb:43:in `send_to'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/call_with.rb:79:in `call_with'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/contracts-0.16.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/elm_install-1.6.1/lib/elm_install.rb:40:in `install'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/elm_install-1.6.1/bin/elm-install:20:in `block (2 levels) in <top (required)>'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
        from C:/Users/code/AppData/Roaming/npm/node_modules/elm-github-install/scripts/dist-1.6.1/elm-install-1.6.1-win32/lib/vendor/ruby/2.2.0/gems/commander-4.4.3/lib/commander/import.rb:5:in `block in <top (required)>'

**Comment by SidneyNemzer** [comment]
I've run into this error too, it's pretty annoying!

From the beginning of the trace, it looks like `git reset --hard` is being run, but it fails with the error `error: unable to create file src/Material/Aux.elm (No such file or directory)`. I assume you're running this on Windows, which doesn't allow files named `Aux` or something stupid like that. The thing is, that file is from an old version of the repo, so why is that the HEAD commit? I'm still not sure how it gets into this state.

I would try these steps, and run elm-github-install in your desired folder between steps to check if it's fixed:

1. Delete the folder `C:/Users/code/.elm-install/github.com/debois/elm-mdl`, which should cause elm-github-install to re-clone that repo.
2. Open  `C:/Users/code/.elm-install/github.com/debois/elm-mdl` and run:  

    ```
    git fetch
    git checkout master
    git reset --hard
    ```
3. Downgrade elm-github-install to 1.0.1

I can't remember exactly how I solved this, although I suspect downgrading will fix it.

**Comment by alexpreiss** [comment]
I was able to get this fixed! I had to manually clone a lot of the packages :/. Also, some packages had dependencies with a weird version, so I did have to add a few packages to the elm-package.json with specified versions. Super annoying but glad it works. Hope this can help some other people using a similar janky codebase ;).
