### ISSUE TITLE
gem elm-install does not work

### ISSUE THREAD

**Issue by martinos** [gdotdesign/elm-github-install#9]
I have rubygems installed on my computer and when I tried to install `elm-install`, it didn't work. I got the following error message.

```
$> gem install elm-install
ERROR:  Could not find a valid gem 'elm-install' (>= 0) in any repository
ERROR:  Possible alternatives: elm_install
```

I looked at the Gemspec I and have found that the gem name is `elm_install` maybe you could correct the command name in the README.md file.

**Comment by gdotdesign** [comment]
Closing this since merged the PR.
